services:
  image-frontend:
    container_name: image-frontend
    build: .
    volumes:
      - ./src:/mnt/src
    ports:
      - 8000:8000
    env_file:
      - .env
    # we need init to kill elm-test when run with "make test"
    # init: true
